Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using PetStore.Exceptions;
using PetStore.Models.ViewModels.Purchases;
using PetStore.Services.ActionServices.PurchasesActionServices.Interfaces;

namespace PetStore.Controllers
{
    public class PurchasesController : Controller
    {
        [Authorize]
        [HttpGet]
        public async Task<ViewResult> Index([FromServices] IPurchasesIndexService indexService, int? page)
        {
            PurchasesIndexViewModel viewModel = await indexService.Handle(page);

            return View(viewModel);
        }

        [HttpGet]
        public ViewResult Create([FromServices] IPurchasesGetCreateService getCreateService, string cartItemsIdsQueryString)
        {
            PurchasesCreateViewModel viewModel = getCreateService.Handle(cartItemsIdsQueryString);

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromServices] IPurchasePostCreateService postCreateService, PurchasesCreateViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await postCreateService.Handle(viewModel);

                    return Redirect("Confirmation");
                }

                return View(viewModel);
            }
            catch (PurchaseValidationException)
            {
                return BadRequest();
            }
        }

        public ViewResult Confirmation()
        {
            return View("Confirmation");
        }
    }
}

Controllers/ToysController.cs
using System;
using System.Collections;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using PetStore.Exceptions;
using PetStore.Models.ViewModels.Toys;
using PetStore.Services.ActionServices.ToysActionServices.Interfaces;
using PetStore.Services.ViewModelServices.ToysViewModelServices.Interfaces;

namespace PetStore.Controllers
{
    public class ToysController : Controller
    {
        [HttpGet]
        public ViewResult Index([FromServices] IToysIndexService indexService, string searchString, int? page)
        {
            return View(indexService.Handle(User, searchString, page));
        }

        [HttpGet]
        public async Task<ActionResult> Details([FromServices] IToysDetailsService detailsService, int id)
        {
            try
            {
                ToysDetailsViewModel viewModel = await detailsService.Handle(User, id);

                return View(viewModel);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
        }

        [Authorize]
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create([FromServices] IToysCreateService createService, ToysCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await createService.Handle(viewModel);
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Edit([FromServices] IToysGetEditService getEditService, int id)
        {
            try
            {
                ToysEditViewModel viewModel = await getEditService.Handle(id);

                return View(viewModel);
            }
            catch (NotFoundException)
            {
                return NotFound();
            }

        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit([FromServices] IToysPostEditService postEditService, ToysEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await postEditService.Handle(viewModel);
                }
                catch (NotFoundException)
                {
                    return NotFound();
                }

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Delete([FromServices] IToyDeleteService deleteService, int id)
        {
            try
            {
                await deleteService.Handle(id);

                return Redirect("/Home");
            }
            catch (NotFoundException)
            {
                return NotFound();
            }

        }
    }
}

Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Toys" asp-action="Create">NewToy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Purchases" asp-action="Index">Purchases</a>
                            </li>
                        }

                        @if (!signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item ml-auto" style="font-size:18px;">
                                <a id="cart-link" class="nav-link text-dark" asp-route="#">Cart(<span id="cart-items-count">0</span>)</a>
                            </li>
                        }

                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item ml-auto">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" class="nav-link btn btn-link " style="width:auto">
                                        Logout @User.Identity.Name
                                    </button>

                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
            <form asp-controller="Purchases" asp-action="Create" method="get" hidden>
                <input id="cart-items-ids" name="cartItemsIdsQueryString" />
                <button id="go-to-cart-btn" type="submit"></button>
            </form>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Rade Culum
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>